server:
  port: 80
eureka:
  client:
    #表示是否将自己注册到注册中心，默认为true
    register-with-eureka: true
    #是否从Eureka Server中住区已有的注册信息，默认为true，单个节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
spring:
  application:
    name: cloud-order-server